<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ProyectoFinca.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- EF Core con proveedor para PostgreSQL -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <!-- Hashing de contraseñas con BCrypt -->
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />

    <!-- JWT — generación y validación de tokens -->
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProyectoFinca.Domain\ProyectoFinca.Domain.csproj" />
    <ProjectReference Include="..\ProyectoFinca.Application\ProyectoFinca.Application.csproj" />
  </ItemGroup>

</Project>
