// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoFinca.Infrastructure.Persistence;

#nullable disable

namespace ProyectoFinca.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815190457_AddSalesOrderServices")]
    partial class AddSalesOrderServices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pos")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pos", "sales_order_status", new[] { "pendiente", "en_proceso", "completada", "facturada", "cancelada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pos", "user_role", new[] { "admin", "cajero", "mesero", "cliente" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("precio_base");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_planes_is_active");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_planes_nombre");

                    b.ToTable("planes", "pos");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.PlanService", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("AsignadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("asignado_en")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("EsObligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_obligatorio");

                    b.Property<int>("OrdenPresentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden_presentacion");

                    b.Property<decimal?>("PrecioEspecial")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("precio_especial");

                    b.HasKey("PlanId", "ServiceId");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_plan_services_service_id");

                    b.ToTable("plan_services", "pos");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<decimal>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCheckIn")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_check_in");

                    b.Property<DateTime?>("FechaCheckOut")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_check_out");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("timestamptz")
                        .HasColumnName("fecha_orden");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_cliente");

                    b.Property<int>("NumeroHuespedes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("numero_huespedes");

                    b.Property<string>("NumeroOrden")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_orden");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5, 4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("porcentaje_impuesto");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("total");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FechaOrden")
                        .HasDatabaseName("ix_sales_orders_fecha_orden");

                    b.HasIndex("NumeroOrden")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_orders_numero_orden");

                    b.HasIndex("PlanId");

                    b.HasIndex("Estado", "FechaOrden")
                        .HasDatabaseName("ix_sales_orders_estado_fecha_orden");

                    b.HasIndex("FechaCheckIn", "FechaCheckOut")
                        .HasDatabaseName("ix_sales_orders_check_in_out");

                    b.HasIndex("UserId", "Estado")
                        .HasDatabaseName("ix_sales_orders_user_id_estado");

                    b.HasIndex("UserId", "FechaOrden")
                        .HasDatabaseName("ix_sales_orders_user_id_fecha_orden");

                    b.ToTable("sales_orders", "pos");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.SalesOrderService", b =>
                {
                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_order_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("AgregadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("agregado_en")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("EraObligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("era_obligatorio");

                    b.Property<decimal>("PrecioCobrado")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("precio_cobrado");

                    b.HasKey("SalesOrderId", "ServiceId");

                    b.HasIndex("SalesOrderId")
                        .HasDatabaseName("ix_sales_order_services_order_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_sales_order_services_service_id");

                    b.ToTable("sales_order_services", "pos");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Categoria")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioAdicional")
                        .HasColumnType("numeric(12, 2)")
                        .HasColumnName("precio_adicional");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("ix_services_categoria");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_services_is_active");

                    b.ToTable("services", "pos");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("Rol")
                        .HasDatabaseName("ix_usuarios_rol");

                    b.ToTable("usuarios", "pos");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.PlanService", b =>
                {
                    b.HasOne("ProyectoFinca.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanServices")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_services_plan");

                    b.HasOne("ProyectoFinca.Domain.Entities.Service", "Service")
                        .WithMany("PlanServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_services_service");

                    b.Navigation("Plan");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.SalesOrder", b =>
                {
                    b.HasOne("ProyectoFinca.Domain.Entities.Plan", "Plan")
                        .WithMany("SalesOrders")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_orders_plan");

                    b.HasOne("ProyectoFinca.Domain.Entities.Usuario", "Usuario")
                        .WithMany("SalesOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_orders_usuario");

                    b.Navigation("Plan");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.SalesOrderService", b =>
                {
                    b.HasOne("ProyectoFinca.Domain.Entities.SalesOrder", "SalesOrder")
                        .WithMany("SalesOrderServices")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_order_services_sales_order");

                    b.HasOne("ProyectoFinca.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_order_services_service");

                    b.Navigation("SalesOrder");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.Plan", b =>
                {
                    b.Navigation("PlanServices");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.SalesOrder", b =>
                {
                    b.Navigation("SalesOrderServices");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.Service", b =>
                {
                    b.Navigation("PlanServices");
                });

            modelBuilder.Entity("ProyectoFinca.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("SalesOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
